name: Run Tests
on: push

jobs:
  pytest:
    name: pytest
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-python@v1
      with:
        python-version: '3.7.5'
        architecture: 'x64'
    - name: Install
      uses: abatilo/actions-poetry@v1.0.0
      with:
        args: install
    - name: update pip
      run: sudo pip install --upgrade pip
    - name: Run pytest
      uses: abatilo/actions-poetry@v1.0.0
      with:
        args: run python -m pytest tests/
