name: Run Tests

on: [push]

jobs:
  pytest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: setup python
        uses: actions/setup-python@v1
        with:
          python-version: "3.7.5"
          architecture: "x64"
      - name: poetry
        uses: dschep/install-poetry-action@v1.2
      - name: Run pytest
        run: |
          python -m pytest /tests
