name: CI

on: [push]

jobs:
  pytest:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Setup Python for use with actions
      uses: actions/setup-python@v1.0.0
      with:
        python-version: "3.7.5"
        architecture: "x64"
    - name: Install
      uses: abatilo/actions-poetry@v1.0.0
      with:
        args: install
    - name: Run pytest
      uses: abatilo/actions-poetry@v1.0.0
      with:
        args: run python -m pytest tests/
