name: Run Tests
on: push

jobs:
  pytest:
    name: pytest
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: update pip
      run: sudo pip install --upgrade pip
    - name: apt install
      run: sudo apt install python3-cffi libsodium-dev build-essential
    - name: Install
      uses: abatilo/actions-poetry@v1.0.0
      with:
        args: install
    - name: Run pytest
      uses: abatilo/actions-poetry@v1.0.0
      with:
        args: run python -m pytest tests/
