name: Run Tests
on: push

jobs:
  pytest:
    name: pytest
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: which gcc
      run: which gcc
    - name: sudo apt upgrade
      run: sudo apt upgrade
    - name: apt install
      run: sudo apt-get install build-essential libffi-dev
    - name: Install
      uses: abatilo/actions-poetry@v1.0.0
      with:
        args: install
    - name: Run pytest
      uses: abatilo/actions-poetry@v1.0.0
      with:
        args: run python -m pytest tests/
